### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by novioleo** [ysh329/naive-hash-table#1]
看了你代码，意识到一个 问题，如果你的空间长度是N。如果我需要存储的数刚好都是k*N，k为正整数，那你对任意一个数p*N，p为正整数，搜索都是遍历咯~时间复杂度就是log n了~要不要试试多段编码的形式来解决这个问题~

**Comment by ysh329** [comment]
我之前对这方面不了解哈[捂脸]，你说的搜索是遍历，没太理解，如果查找的话直接通过`value`找到`address`，就定位到了呀。

多段编码是啥呀[捂脸]

**Comment by novioleo** [comment]
你可以自己测试下，如果你的hash表中存储8,16,24,32,40,48,56,64。hash表的大小设为8，然后你输出取出每一个所需要for循环的次数~
原则上应该是1,2,3,4,5,6,7,8

**Comment by ysh329** [comment]
@novioleo 你说的对，是存在这个问题哈……多段编码是为了解决这个问题嘛？我搜了下，没有讲哈希表和多段编码的，是不是关键词不准确呀

**Comment by novioleo** [comment]
唔、关键字不对~~不过概念大概就是如果把每个元素除以长度的余数几乎都集中在一个值上面，那么就会引起性能问题。那么为了解决，就引入两个值，a和b，a表示哈希表长度，b表示一个比a小的数，然后当前值与a，b分别相除得到余数p，q，用p、q共同来表示一个地址。大概逻辑是这个。名字的话我也忘了。反正就是为规避这个情况的发生。

**Comment by ysh329** [comment]
@novioleo 大佬大佬，留个邮箱加好友私聊

**Comment by novioleo** [comment]
菜鸡一个。nsnovio@gmail.com @ysh329
